server:
  port: 8080 # El puerto público principal

spring:
  application:
    name: api-gateway-arcbank
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 45s
      # 1. ESTO SOLUCIONA LOS "MULTIPLE VALUES" (Deduplica los headers)
      default-filters:
        - "DeduplicateResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials"
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      

      routes:
        # RUTA 1: CLIENTES
        - id: clientes-service
          uri: http://service-clientes:80
          predicates:
            - Path=/arcbank/api/v1/clientes/**
          filters:
            - StripPrefix=1

        # RUTA 2: PERSONAS
        - id: personas-service
          uri: http://service-clientes:80
          predicates:
            - Path=/arcbank/api/v1/personas/**
          filters:
            - StripPrefix=1

        # RUTA 3: EMPRESAS
        - id: empresas-service
          uri: http://service-clientes:80
          predicates:
            - Path=/arcbank/api/v1/empresas/**
          filters:
            - StripPrefix=1

        # RUTA 4: CUENTAS AHORROS
        - id: cuentas-ahorros-service
          uri: http://service-cuentas:80
          predicates:
            - Path=/arcbank/api/v1/cuentas/ahorros/**
          filters:
            - StripPrefix=1

        # RUTA 5: TASAS DE INTERÉS
        - id: tasas-service
          uri: http://service-cuentas:80
          predicates:
            - Path=/arcbank/api/v1/cuentas/tasas/**
          filters:
            - StripPrefix=1

        # RUTA 6: TIPOS DE CUENTA
        - id: tipos-cuenta-service
          uri: http://service-cuentas:80
          predicates:
            - Path=/arcbank/api/v1/cuentas/tipos-cuenta/**
          filters:
            - StripPrefix=1

        # RUTA 7: TRANSACCIONES
        - id: transacciones-service
          uri: http://service-transacciones:80
          predicates:
            - Path=/arcbank/api/transacciones/**
          filters:
            - StripPrefix=1

        # RUTA 8: BANCOS
        - id: bancos-service
          uri: http://service-transacciones:80
          predicates:
            - Path=/arcbank/api/bancos/**
          filters:
            - StripPrefix=1

        # RUTA 9: SUCURSALES
        - id: sucursales-service
          uri: http://service-sucursales:80
          predicates:
            - Path=/arcbank/api/v1/sucursales/**
          filters:
            - StripPrefix=1

        # RUTA 10: CORE
        - id: core-service
          uri: http://service-transacciones:80
          predicates:
            - Path=/arcbank/api/core/**
          filters:
            - StripPrefix=1
        
        # RUTA 11: WEBHOOKS
        - id: webhook-incoming
          uri: http://service-transacciones:80
          predicates:
            - Path=/arcbank/api/incoming/**
          filters:
            - StripPrefix=1

        # RUTAS DE DOCUMENTACIÓN
        - id: clientes-docs
          uri: http://service-clientes:80
          predicates:
            - Path=/arcbank/v3/api-docs/clientes/**
          filters:
            - RewritePath=/arcbank/v3/api-docs/clientes/(.*), /v3/api-docs/$1
            - RewritePath=/v3/api-docs/clientes/(.*), /v3/api-docs/$1

        - id: cuentas-docs
          uri: http://service-cuentas:80
          predicates:
            - Path=/arcbank/v3/api-docs/cuentas/**
          filters:
            - RewritePath=/arcbank/v3/api-docs/cuentas/(.*), /v3/api-docs/$1
            - RewritePath=/v3/api-docs/cuentas/(.*), /v3/api-docs/$1

        - id: transacciones-docs
          uri: http://service-transacciones:80
          predicates:
            - Path=/arcbank/v3/api-docs/transacciones/**
          filters:
            - RewritePath=/arcbank/v3/api-docs/transacciones/(.*), /v3/api-docs/$1
            - RewritePath=/v3/api-docs/transacciones/(.*), /v3/api-docs/$1

        - id: sucursales-docs
          uri: http://service-sucursales:80
          predicates:
            - Path=/arcbank/v3/api-docs/sucursales/**
          filters:
            - RewritePath=/arcbank/v3/api-docs/sucursales/(.*), /v3/api-docs/$1
            - RewritePath=/v3/api-docs/sucursales/(.*), /v3/api-docs/$1

# Swagger UI Centralizado
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: 1. Micro Clientes
        url: /v3/api-docs/clientes
      - name: 2. Micro Cuentas
        url: /v3/api-docs/cuentas
      - name: 3. MS Transacción
        url: /v3/api-docs/transacciones
      - name: 4. Micro Sucursales
        url: /v3/api-docs/sucursales

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO

# Configuración de Integración APIM / Switch
cognito:
  token-url: ${COGNITO_TOKEN_URL:https://auth-banca-digiconecu-dev-lhd4go.auth.us-east-2.amazoncognito.com/oauth2/token}
  client-id: ${COGNITO_CLIENT_ID:3jprfuk1phejsm0sjr8p50n91e}
  client-secret: ${COGNITO_CLIENT_SECRET:change-me}

apim:
  base-url: ${APIM_BASE_URL:https://gf0js7uezg.execute-api.us-east-2.amazonaws.com/dev}
